
#undef COMBO_COUNT
#define COMBO_COUNT 9

#undef COMBO_TERM
#define COMBO_TERM 80

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#undef FORCE_NKRO
#define FORCE_NKRO 

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 300

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 16

#undef MOUSEKEY_SLOW_SPEED
#define MOUSEKEY_SLOW_SPEED 1

#undef MOUSEKEY_FAST_SPEED
#define MOUSEKEY_FAST_SPEED 7

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 80

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 16

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 4

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 180

#undef NO_ACTION_FUNCTION
#define NO_ACTION_FUNCTION 

#undef NO_ACTION_MACRO
#define NO_ACTION_MACRO 

#undef NO_DEBUG
#define NO_DEBUG 

#undef NO_PRINT
#define NO_PRINT 

#undef ONESHOT_TAP_TOGGLE
#define ONESHOT_TAP_TOGGLE 5

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 4000

#undef TAPPING_TERM
#define TAPPING_TERM 110

#undef TAPPING_TERM_TAP_DANCE
#define TAPPING_TERM_TAP_DANCE 270

#undef UNICODE_SELECTED_MODES
#define UNICODE_SELECTED_MODES UC_OSX, UC_WINC

#undef TURBO_SIGNAL_TIMEOUT
#define TURBO_SIGNAL_TIMEOUT 100

#undef TURBO_NO_SIGNAL_TIMEOUT
#define TURBO_NO_SIGNAL_TIMEOUT 200

#undef APP_SWITCH_TIMEOUT
#define APP_SWITCH_TIMEOUT 250

#undef RGBLIGHT_ENABLE
#define RGBLIGHT_ENABLE yes

#undef AUDIO_CLICKY
#define AUDIO_CLICKY 

#undef STARTUP_SONG
#define STARTUP_SONG SONG(NO_SOUND)
