
#undef COMBO_COUNT
#define COMBO_COUNT 9

#undef COMBO_TERM
#define COMBO_TERM 80

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#undef FORCE_NKRO
#define FORCE_NKRO 

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 300

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 16

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 80

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 4

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 180

#undef NO_ACTION_FUNCTION
#define NO_ACTION_FUNCTION 

#undef NO_ACTION_MACRO
#define NO_ACTION_MACRO 

<<<<<<< HEAD
#undef APP_SWITCH_TIMEOUT
#define APP_SWITCH_TIMEOUT 500
=======
#undef NO_ACTION_ONESHOT
#define NO_ACTION_ONESHOT 
>>>>>>> 4ec22ef... feature-11 Remove useless lights

#undef NO_DEBUG
#define NO_DEBUG 

#undef NO_PRINT
#define NO_PRINT 

<<<<<<< HEAD
#undef ONESHOT_TAP_TOGGLE
#define ONESHOT_TAP_TOGGLE 5

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 4000

=======
>>>>>>> 4ec22ef... feature-11 Remove useless lights
#undef TAPPING_TERM
#define TAPPING_TERM 110

#undef TAPPING_TERM_TAP_DANCE
#define TAPPING_TERM_TAP_DANCE 270

#undef UNICODE_SELECTED_MODES
#define UNICODE_SELECTED_MODES UC_OSX, UC_WINC

#undef AUDIO_CLICKY
#define AUDIO_CLICKY 

#undef STARTUP_SONG
#define STARTUP_SONG SONG(NO_SOUND)

#undef DISABLE_RGB_MATRIX_SOLID_COLOR
#define DISABLE_RGB_MATRIX_SOLID_COLOR 

#undef DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_ALPHAS_MODS 

#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT 

#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL 

#undef DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_SAT 

#undef DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT 

#undef DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL 

#undef DISABLE_RGB_MATRIX_BAND_VAL
#define DISABLE_RGB_MATRIX_BAND_VAL 

#undef DISABLE_RGB_MATRIX_BREATHING
#define DISABLE_RGB_MATRIX_BREATHING 

#undef DISABLE_RGB_MATRIX_CYCLE_ALL
#define DISABLE_RGB_MATRIX_CYCLE_ALL 

#undef DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN 

#undef DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL 

#undef DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL 

#undef DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#define DISABLE_RGB_MATRIX_CYCLE_SPIRAL 

#undef DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN 

#undef DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_DUAL_BEACON 

#undef DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN 

#undef DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS 

#undef DISABLE_RGB_MATRIX_MULTISPLASH
#define DISABLE_RGB_MATRIX_MULTISPLASH 

#undef DISABLE_RGB_MATRIX_RAINBOW_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_BEACON 

#undef DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON 

#undef DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS 

#undef DISABLE_RGB_MATRIX_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS 

#undef DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE 

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE 

#undef DISABLE_RGB_MATRIX_SOLID_SPLASH
#define DISABLE_RGB_MATRIX_SOLID_SPLASH 

#undef DISABLE_RGB_MATRIX_SPLASH
#define DISABLE_RGB_MATRIX_SPLASH 

#undef DISABLE_RGB_MATRIX_TYPING_HEATMAP
#define DISABLE_RGB_MATRIX_TYPING_HEATMAP 

#undef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS 
