// https://docs.qmk.fm/#/config_options

#pragma once

#undef COMBO_COUNT
#undef COMBO_TERM
#undef FORCE_NKRO
#undef INTERRUPTION_TIMEOUT
#undef LEADER_TIMEOUT
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#undef TAPPING_TERM
#undef TAPPING_TERM_TAP_DANCE

#define COMBO_COUNT 6
#define COMBO_TERM 130
#define FORCE_NKRO 
#define INTERRUPTION_TIMEOUT 60
#define LEADER_TIMEOUT 300
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 150
#define TAPPING_TERM 130
#define TAPPING_TERM_TAP_DANCE 270
#define UNICODE_SELECTED_MODES UC_OSX, UC_WINC