
#undef COMBO_COUNT
#define COMBO_COUNT 9

#undef COMBO_TERM
#define COMBO_TERM 80

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#undef FORCE_NKRO
#define FORCE_NKRO 

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 300

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 20

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 11

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 60

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 4

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 150

#undef TAPPING_TERM
#define TAPPING_TERM 110

#undef TAPPING_TERM_TAP_DANCE
#define TAPPING_TERM_TAP_DANCE 270

#undef UNICODE_SELECTED_MODES
#define UNICODE_SELECTED_MODES UC_OSX, UC_WINC

#undef NO_ACTION_MACRO
#define NO_ACTION_MACRO 

#undef NO_ACTION_FUNCTION
#define NO_ACTION_FUNCTION 

#undef NO_DEBUG
#define NO_DEBUG 

#undef NO_PRINT
#define NO_PRINT 

#undef NO_ACTION_ONESHOT
#define NO_ACTION_ONESHOT 
